# Site settings
title: Game Developer
email:  
description: > # keep this and put description below
  Unity Programmer
url: "https://k-a4.github.io/Portfolio/" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/"
github_username: k-a4
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
